spring.application.name=Aplicacion gestion de clientes

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/CRM
spring.datasource.username=postgres
spring.datasource.password=3436
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#Crear tablas solas
# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
